#! /usr/bin/env python
# -*- python -*-

"""Prints out whether words might be in the dictionary or not."""

import sys, gzip, cPickle
import bloom

# Poor man's argument handling
skipMisses = '-s' in sys.argv
if skipMisses:
    sys.argv.remove ('-s')

showFPR = '-f' in sys.argv
if showFPR:
    sys.argv.remove ('-f')

wordstocheck = sys.argv[1:]

# Load up our special data structure. cPickle loads up a preexisting
# BloomFilter object from disk and returns it to us. The class is
# implemented in bloom.py.
bf = cPickle.load (gzip.GzipFile ('dictbf.dat.gz', 'rb', 9))

# Compute the false-positive rate of the filter.
# FIXME: do something useful with this number?
fp = bf.fprate ()

for word in wordstocheck:
    if bf.maycontain (word):
        print word, 'MIGHT BE in the dictionary'
    elif not skipMisses:
        print word, 'is DEFINITELY NOT in the dictionary'

if showFPR:
    print '(Expected false-positive rate is %.1f%%)' % (100. * fp)
